:fashion:
  -
    :title: true-to-you beauty
    :collection: ["001", "002"]
  -
    :title: Most Likely to Seduce
    :collection: ["003", "004", "005"]
  -
    :title: 8 New Sexy Essentials
    :collection: ["006", "007", "008"]
  -
    :title: The Hot Hues for Spring
    :collection: ["009", "010", "011"]
  -
    :title: "Isaac's Elements of Style"
    :collection: ["012", "013", "014"]
  -
    :title: Day-to-Night Denim
    :collection: ["015", "016", "017"]
  -
    :title: Swept Away
    :collection: ["018", "019", "020"]
  -
    :title: Golden Girl
    :collection: ["021", "022", "023"]
  -
    :title: Wild Thing
    :collection: ["024", "025", "026", "027"]
  -
    :title: Crush the Competition
    :collection: ["028", "029", "030"]

:beauty:
  -
    :title: clear skin every day!
    :collection: ["001", "002"]
  -
    :title: lighten up your look
    :collection: ["003"]
  -
    :title: Fire your hired guns!
    :collection: ["004"]
  -
    :title: Steal the Spotlight
    :collection: ["005"]
  -
    :title: Bold, Lusty Lips
    :collection: ["006"]
  -
    :title: easy summer hair
    :collection: ["007", "008"]
  -
    :title: Party prep!
    :collection: ["009", "010"]
  -
    :title: GIFTS FROM THE SEA
    :collection: ["011", "012"]
  -
    :title: Take it all off!
    :collection: ["013"]
  -
    :title: look radiant
    :collection: ["014", "015"]
  -
    :title: The sundamentals
    :collection: ["016", "017"]
  -
    :title: gam slam!
    :collection: ["018"]
  -
    :title: YOU GOT GAME
    :collection: ["019", "020", "021"]
  -
    :title: SPA FOR A DAY
    :collection: ["022", "023", "024", "025"]

:covers:
  -
    :title: Katy Perry
    :collection: ["01", "02", "03"]
  -
    :title: Fergie
    :collection: ["04", "05", "06"]
  -
    :title: Rihanna
    :collection: ["07"]
  -
    :title: Jessica Alba
    :collection: ["08"]
  -
    :title: Anna Faris
    :collection: ["09"]
  -
    :title: Kristen Bell
    :collection: ["10"]
  -
    :title: Hayden Panettiere
    :collection: ["11"]
  -
    :title: Katherine Heigl
    :collection: ["12"]
  -
    :title: Keira Knightley
    :collection: ["13"]
  -
    :title: Faith Hill
    :collection: ["14"]
  -
    :title: Mariah
    :collection: ["15"]
